source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '6.0'
inhibit_all_warnings!

xcodeproj 'LGViewControllersDemo'

target 'LGViewControllersDemo' do
    pod 'LGViewControllers', :path => '../'
end
